name: To-message
on:
    push:
        branches: 'main'
jobs:
    check-and-publish:
        name: "Test job"
        runs-on: rockylinux:9.2-minimal #ubuntu-latest
        steps:
            - name: "telegram Notification"
              uses: "appleboy/telegram-action@master"
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                args: New version publish 9.2-minimal on main!


