name: To-message
on:
    push:
        branches: ['master','main']
    
jobs:
    check-and-publish:
        name: "Test job"
        runs-on: ubuntu-latest
        steps:
            - name: "telegram Notification"
              uses: "appleboy/telegram-action@master"
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                args: The ${{github.event_name}} by name actor is ${{github.actor}} on repo ${{github.repositoryUrl}} and runner ${{runner.arch}} ${{runner.name}} ${{runner.os}} ${{runner.temp}} ${{runner.tool_cache}}  


