name: To-message
on:
    push:
        branches: ['master','main']
jobs:
    check-and-publish:
        name: "Test job"
        runs-on: ubuntu-latest
        steps:
            - name: "telegram Notification"
              uses: "appleboy/telegram-action@master"
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                args: New version publish only use ubuntu-latest on main! https://github.com/actions/runner-images/tree/main


