name: To-message
on:
    push:
        branches: ['master','main']
    
jobs:
    check-and-publish:
        name: "Test job"
        runs-on: ubuntu-latest
        steps:
            - name: "telegram Notification"
              uses: "appleboy/telegram-action@master"
              with:
                to: ${{ secrets.TELEGRAM_CHAT_ID }}
                token: ${{ secrets.TELEGRAM_TOKEN }}
                # args: "The ${{github.event_name}} by name actor is ${{github.actor}} on repo ${{github.repositoryUrl}} 
                #       \nall github ${{ toJson(github) }}
                #       \nall env ${{toJson(env)}}
                #       \nall job ${{ toJson(job) }}
                #       \nall steps ${{ toJson(steps) }}
                #       \nall runner ${{toJson(runner)}}
                #       \nall secrets ${{ toJson(secrets) }}
                #       \nall strategy ${{ toJson(strategy) }}
                #       \nall matrix ${{ toJson(matrix) }}
                #       \nall needs ${{ toJson(needs) }}
                #       \nall inputs ${{ toJson(inputs) }}"
                args: "The ${{github.event_name}} by name actor is ${{github.actor}} on repo ${{github.repository}}
                       \n
                       \nPre-commit:${{github.event.before}} and him url ${{github.event.repository.url}}/commit/${{github.event.before}}
                       \nNow-commit:${{github.event.after}} and him url https://github.com/Petr16/webhook-test/commit/${{github.event.after}}
                       \nName:${{github.event.commits[0].message}}
                       \nTime:${{github.event.commits[0].timestamp}}
                       \nAutor:${{toJson(github.event.commits[0].author)}}
                       \nCommitter:${{toJson(github.event.commits[0].committer)}}
                       \nCompare:${{github.event.compare}}
                       \nPusher:${{toJson(github.event.pusher)}}"



